root: ./docs/

redirects:
  install-harperdb: deployments/install-harper/README.md
  install-harperdb/linux: deployments/install-harper/linux.md
  install-harperdb/other: deployments/install-harper/README.md
  install-harperdb/docker: deployments/install-harper/README.md
  install-harperdb/mac: deployments/install-harper/README.md
  install-harperdb/windows: deployments/install-harper/README.md
  install-harperdb/linux-quickstart: deployments/install-harper/linux.md
  install-harperdb/offline: deployments/install-harper/README.md
  install-harperdb/node-ver-requirement: deployments/install-harper/README.md
  deployments/install-harperdb: deployments/install-harper/README.md
  deployments/install-harperdb/linux: deployments/install-harper/linux.md
  harperdb-studio: administration/harper-studio/README.md
  harperdb-studio/create-account: administration/harper-studio/create-account.md
  harperdb-studio/login-password-reset: administration/harper-studio/login-password-reset.md
  harperdb-studio/resources: administration/harper-studio/resources.md
  harperdb-studio/organizations: administration/harper-studio/organizations.md
  harperdb-studio/instances: administration/harper-studio/instances.md
  harperdb-studio/query-instance-data: administration/harper-studio/query-instance-data.md
  harperdb-studio/manage-schemas-browse-data: administration/harper-studio/manage-databases-browse-data.md
  harperdb-studio/manage-charts: administration/harper-studio/manage-charts.md
  harperdb-studio/manage-clustering: administration/harper-studio/manage-replication.md
  harperdb-studio/manage-instance-users: administration/harper-studio/manage-instance-users.md
  harperdb-studio/manage-instance-roles: administration/harper-studio/manage-instance-users.md
  harperdb-studio/manage-functions: administration/harper-studio/manage-applications.md
  harperdb-studio/instance-metrics: administration/harper-studio/instance-metrics.md
  harperdb-studio/instance-configuration: administration/harper-studio/instance-configuration.md
  harperdb-studio/enable-mixed-content: administration/harper-studio/enable-mixed-content.md
#  administration/harperdb-studio: administration/harper-studio/README.md
#  administration/harperdb-studio/create-account: administration/harper-studio/create-account.md
#  administration/harperdb-studio/enable-mixed-content: administration/harper-studio/enable-mixed-content.md
#  administration/harperdb-studio/instance-configuration: administration/harper-studio/instance-configuration.md
#  administration/harperdb-studio/instance-metrics: administration/harper-studio/instance-metrics.md
#  administration/harperdb-studio/instances: administration/harper-studio/instances.md
#  administration/harperdb-studio/login-password-reset: administration/harper-studio/login-password-reset.md
#  administration/harperdb-studio/manage-applications: administration/harper-studio/manage-applications.md
#  administration/harperdb-studio/manage-charts: administration/harper-studio/README.md
#  administration/harperdb-studio/manage-databases-browse-data: administration/harper-studio/manage-databases-browse-data.md
#  administration/harperdb-studio/manage-instance-roles: administration/harper-studio/manage-instance-roles.md
#  administration/harperdb-studio/manage-instance-users: administration/harper-studio/manage-instance-users.md
#  administration/harperdb-studio/manage-replication: administration/harper-studio/manage-replication.md
#  administration/harperdb-studio/organizations: administration/harper-studio/organizations.md
  harperdb-cloud: deployments/harper-cloud/README.md
  harperdb-cloud/iops-impact: deployments/harper-cloud/iops-impact.md
  harperdb-cloud/instance-size-hardware-specs: deployments/harper-cloud/instance-size-hardware-specs.md
  harperdb-cloud/alarms: deployments/harper-cloud/alarms.md
  harperdb-cloud/verizon-5g-wavelength-instances: deployments/harper-cloud/verizon-5g-wavelength-instances.md
  deployments/harperdb-cloud: deployments/harper-cloud/README.md
  deployments/harperdb-cloud/iops-impact: deployments/harper-cloud/iops-impact.md
  deployments/harperdb-cloud/instance-size-hardware-specs: deployments/harper-cloud/instance-size-hardware-specs.md
  deployments/harperdb-cloud/alarms: deployments/harper-cloud/alarms.md
  deployments/harperdb-cloud/verizon-5g-wavelength-instances: deployments/harper-cloud/verizon-5g-wavelength-instances.md
  security: developers/security/README.md
  security/jwt-auth: developers/security/jwt-auth.md
  security/basic-auth: developers/security/basic-auth.md
  security/configuration: developers/security/configuration.md)
  security/users-and-roles: developers/security/users-and-roles.md)
  clustering: developers/clustering/README.md
  clustering/requirements-and-definitions: developers/clustering/requirements-and-definitions.md
  clustering/creating-a-cluster-user: developers/clustering/creating-a-cluster-user.md
  clustering/naming-a-node: developers/clustering/naming-a-node.md
  clustering/enabling-clustering: developers/clustering/enabling-clustering.md
  clustering/establishing-routes: developers/clustering/establishing-routes.md
  clustering/subscription-overview: developers/clustering/subscription-overview.md
  clustering/managing-subscriptions: developers/clustering/managing-subscriptions.md
  clustering/things-worth-knowing: developers/clustering/things-worth-knowing.md
  custom-functions: developers/applications/README.md
  custom-functions/define-routes: developers/applications/define-routes.md
  custom-functions/using-npm-git: developers/custom-functions/create-project.md
  custom-functions/custom-functions-operations: developers/components/operations.md
  custom-functions/debugging-custom-function: developers/applications/debugging.md
  custom-functions/example-projects: developers/applications/example-projects.md
  add-ons-and-sdks: developers/components/README.md
  add-ons-and-sdks/google-data-studio: developers/components/google-data-studio.md
  sql-guide: developers/sql-guide/README.md
  sql-guide/features-matrix: developers/sql-guide/features-matrix.md
  sql-guide/insert: developers/sql-guide/README.md
  sql-guide/update: developers/sql-guide/README.md
  sql-guide/delete: developers/sql-guide/README.md
  sql-guide/select: developers/sql-guide/README.md
  sql-guide/joins: developers/sql-guide/README.md
  sql-guide/date-functions: developers/sql-guide/date-functions.md
  sql-guide/reserved-word: developers/sql-guide/reserved-word.md
  sql-guide/functions: developers/sql-guide/functions.md
  sql-guide/json-search: developers/sql-guide/json-search.md
  sql-guide/sql-geospatial-functions: developers/sql-guide/sql-geospatial-functions.md
  sql-guide/sql-geospatial-functions/geoarea: developers/sql-guide/sql-geospatial-functions.md
  sql-guide/sql-geospatial-functions/geolength: developers/sql-guide/sql-geospatial-functions.md
  sql-guide/sql-geospatial-functions/geodifference: developers/sql-guide/sql-geospatial-functions.md
  sql-guide/sql-geospatial-functions/geodistance: developers/sql-guide/sql-geospatial-functions.md
  sql-guide/sql-geospatial-functions/geonear: developers/sql-guide/sql-geospatial-functions.md
  sql-guide/sql-geospatial-functions/geocontains: developers/sql-guide/sql-geospatial-functions.md
  sql-guide/sql-geospatial-functions/geoequal: developers/sql-guide/sql-geospatial-functions.md
  sql-guide/sql-geospatial-functions/geocrosses: developers/sql-guide/sql-geospatial-functions.md
  sql-guide/sql-geospatial-functions/geoconvert: developers/sql-guide/sql-geospatial-functions.md
  harperdb-cli: deployments/harper-cli.md
  deployments/harperdb-cli: deployments/harper-cli.md
  configuration: deployments/configuration.md
  logging: administration/logging/logging.md
  transaction-logging: administration/logging/transaction-logging.md
  audit-logging: administration/logging/audit-logging.md
  jobs: administration/jobs.md
  upgrade-hdb-instance: deployments/upgrade-hdb-instance.md
  reference: technical-details/reference/README.md
  reference/storage-algorithm: technical-details/reference/storage-algorithm.md
  reference/dynamic-schema: technical-details/reference/dynamic-schema.md
  reference/data-types: technical-details/reference/data-types.md
  reference/content-types: technical-details/reference/content-types.md
  reference/headers: technical-details/reference/headers.md
  reference/limits: technical-details/reference/limits.md
  release-notes: technical-details/release-notes/README.md
  operations-api: developers/operations-api/README.md
  rest: developers/rest.md
  api: developers/operations-api/README.md
  administration/harperdb-studio/query-instance-data: developers/rest.md

