root: ./docs/

redirects:
  install-harperdb/other: install-harperdb/README.md
  install-harperdb/docker: install-harperdb/README.md
  install-harperdb/mac: install-harperdb/README.md
  install-harperdb/windows: install-harperdb/README.md
  install-harperdb/linux-quickstart: install-harperdb/linux.md
  install-harperdb/offline: install-harperdb/README.md
  install-harperdb/node-ver-requirement: install-harperdb/README.md
  add-ons-and-sdks: components/README.md
  add-ons-and-sdks/google-data-studio: components/google-data-studio.md
  getting-started: getting-started.md
  custom-functions/using-npm-git: custom-functions/create-project.md
  custom-functions/debugging-custom-function: applications/debugging.md
  custom-functions/example-projects: applications/example-projects.md
  custom-functions/define-routes: applications/define-routes.md
  custom-functions/custom-functions-operations: components/operations.md
  custom-functions: applications/README.md
