import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [{ type: 'autogenerated', dirName: 'getting-started' }],
  developersSidebar:     [{ type: 'autogenerated', dirName: 'developers' }],
  administrationSidebar: [{ type: 'autogenerated', dirName: 'administration' }],
  deploymentsSidebar:    [{ type: 'autogenerated', dirName: 'deployments' }],
  technicalDetailsSidebar:[{ type: 'autogenerated', dirName: 'technical-details' }],
};

export default sidebars;
