import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsLearn: SidebarsConfig = {
	learnSidebar: [
		{
			type: 'doc',
			id: 'index',
			label: 'Welcome',
		},
		{
			type: 'category',
			label: 'Getting Started',
			collapsible: false,
			className: 'learn-category-header',
			items: [{ type: 'autogenerated', dirName: 'getting-started' }],
		},
		{
			type: 'category',
			label: 'Developers',
			collapsible: false,
			className: 'learn-category-header',
			items: [{ type: 'autogenerated', dirName: 'developers' }],
		},
		{
			type: 'category',
			label: 'Administration',
			collapsible: false,
			className: 'learn-category-header',
			items: [{ type: 'autogenerated', dirName: 'administration' }],
		},
	],
};

export default sidebarsLearn;
