import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsFabric: SidebarsConfig = {
	fabricSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebarsFabric;
