import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Harper Docs',
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Developers',
      link: {
        type: 'generated-index',
        title: 'Developer Documentation',
        description: 'Comprehensive guides and references for building applications with HarperDB',
        keywords: ['developers', 'api', 'applications']
      },
      items: [{type: 'autogenerated', dirName: 'developers'}],
    },
    {
      type: 'category',
      label: 'Administration',
      items: [{type: 'autogenerated', dirName: 'administration'}],
    },
    {
      type: 'category',
      label: 'Deployments',
      items: [{type: 'autogenerated', dirName: 'deployments'}],
    },
    {
      type: 'category',
      label: 'Technical Details',
      items: [{type: 'autogenerated', dirName: 'technical-details'}],
    },
  ],
};

export default sidebars;