import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Fully autogenerated sidebar
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;