openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /create_table:
    post:
      description: Create a new table within a database.
      requestBody:
        content:
          application/json:
            operation:
              type: string
              value: create_table
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              message: string
              value: table 'dev.dog' successfully created.