openapi: 3.0.3
info:
  title: Swagger HarperDB - OpenAPI 3.0
  version: 1.0.0
paths:
  /create_table:
    post:
      summary: Create a new table within a database.
      requestBody:
        description: Create a new pet in the store
        required: true
        content:
          application/json:
            schema:
              required:
                - operation
                - table
                - primary_key
              properties:
                operation:
                  type: string
                  example: create_table
                database:
                  type: string
                  example: dev
                  description: name of the database where you want your table to live. If the database does not exist, it will be created. If the `database` property is not provided it will default to `data`.
                table:
                  type: string
                  example: dog
                  description: name of the table you are creating.
                primary_key:
                  type: string
                  example: id
                  description: primary key for the table
                expiration:
                  type: integer
                  example: 3600
                  description: Specifies the time-to-live or expiration of records in the table before they are evicted (records are not evicted on any timer if not specified). This is specified in seconds.
                attributes:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                        description: The name of the attribute
                      indexed:
                        type: boolean
                        description: Indicates if the attribute should be indexed
                      type:
                        type: string
                        description:  Specifies the data type of the attribute.
                        enum:
                          - String
                          - Int
                          - Float
                          - Date
                          - ID
                          - Any
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: table 'dev.dog' successfully created.