openapi: 3.0.0
info:
  title: HarperDB 4.1.0
  description: >-
    Welcome to HarperDB API reference!


    Here you find interface descriptions for all HarperDB API operations with
    example code.  To see example code in various programming languages, use the
    language dropdown in the top navigation to select your desired coding
    language. Use the Run in Postman button, at the top right, to open the
    HarperDB API operations as a Postman collection where you can edit and
    modify each request.


    • <a href="https://studio.harperdb.io/">HarperDB Studio</a>


    • <a href="https://docs.harperdb.io/">HarperDB Documentation</a>


    • <a href="https://harperdb.io/docs/getting-started/">Installation & Getting
    Started</a>


    • Authentication Guides: <a
    href="https://harperdb.io/docs/security/authentication/">Basic Auth</a> or
    <a href="https://harperdb.io/docs/security/jwt-authentication/">Token
    Auth</a>


    • <a href="https://harperdbhelp.zendesk.com/hc/en-us/requests/new">Submit a
    HarperDB Support Request</a>


    • <a href="https://olddocs.harperdb.io">Past Release API Documentation</a>
  version: 1.0.0
servers:
  - url: http://{{hdb_endpoint}}
tags:
  - name: QuickStart Examples
paths:
  /:
    post:
      tags:
        - QuickStart Examples
      summary: Select Dogs and Join Breed
      description: >-
        Here's a more complex SQL command joining the breed table with the dog
        table.  We will also pull only the pups belonging to Kyle, Zach, and
        Stephen.
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\n    \"operation\": \"sql\",\n    \"sql\": \"SELECT d.id,
                d.dog_name, d.owner_name, b.name, b.section FROM dev.dog AS d
                INNER JOIN dev.breed AS b ON d.breed_id = b.id WHERE
                d.owner_name IN ('Kyle', 'Zach', 'Stephen') AND b.section =
                'Mutt' ORDER BY d.dog_name\"\n}"
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Origin, Accept-Encoding
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '381'
            Date:
              schema:
                type: string
                example: Fri, 15 Jan 2021 22:24:18 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 4
                  dog_name: Billy
                  owner_name: Zach
                  name: LABRADOR / GREAT DANE MIX
                  section: Mutt
                - id: 8
                  dog_name: Gemma
                  owner_name: Stephen
                  name: SHORT HAIRED SETTER MIX
                  section: Mutt
                - id: 2
                  dog_name: Harper
                  owner_name: Stephen
                  name: HUSKY MIX
                  section: Mutt
                - id: 5
                  dog_name: Rose Merry
                  owner_name: Zach
                  name: TERRIER MIX
                  section: Mutt
