openapi: 3.0.3
info:
  title: Swagger HarperDB - OpenAPI 3.0
  version: 1.0.0
paths:
  /create_table:
    post:
      summary: Create a new table within a database.
      description: Create a new table within a database.
      parameters:
        - name: operation
          in: query
          description: must always be `create_table`
          required: true
          schema:
            type: string
        - name: database
          in: query
          description: name of the database where you want your table to live. If the database does not exist, it will be created. If the `database` property is not provided it will default to `data`.
          required: false
          schema:
            type: string
        - name: primary_key
          in: query
          description: primary key for the table
          required: true
          schema:
            type: string
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              properties:
                operation:
                  type: string
                  example: create_table
                database:
                  type: string
                  example: dev
                primary_key:
                  type: string
                  example: id
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                message: table 'dev.dog' successfully created.